---
  name: Hugo CI & Deploy
  on:
    push:
      branches:
        - main
  jobs:
    build:
      name: Build and deploy the website
      runs-on: ubuntu-latest
      environment: deploy
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          
        - name: Setup Hugo
          uses: peaceiris/actions-hugo@v2
          with:
            hugo-version: latest
            extended: true

        - name: Build website with Hugo
          run: hugo --minify
          working-directory: ./quickstart

        - name: Deploy website with rsync
          uses: burnett01/rsync-deployments@5.2
          with:
            switches: -avzr --delete
            path: src/
            remote_path: ${{ secrets.DEPLOY_PATH }}
            remote_host: ${{ secrets.DEPLOY_HOST }}
            remote_user: ${{ secrets.DEPLOY_USER }}
            remote_key: ${{ secrets.DEPLOY_KEY }}
  